### ISSUE TITLE
Implement example: 7GUIs Temperature Converter

### ISSUE THREAD

**Issue by tbreuss** [tbreuss/mithril-by-examples#14]
The implementation must be integrated in this Markdown file: 

- https://github.com/tbreuss/mithril-by-examples/blob/main/examples/7gui-temperature-converter.md

And the content should be formatted like here for example:

- https://github.com/tbreuss/mithril-by-examples/blob/main/examples/routing.md

If you have any question, leave a message in the comments.

**Comment by narayand16** [comment]
@tbreuss  Can you assign this issue to me ?

**Comment by tbreuss** [comment]
I have assigned it to you. 

Please note, that the implementation should be placed within the above markdown file.
It will then "compiled" and built and in the end referenced to flems via a automatically generated link button.

If you have any question on that, let me know.
