### ISSUE TITLE
Link author with contributor page

### ISSUE THREAD

**Issue by tbreuss** [tbreuss/mithril-by-examples#38]
Link author displayed on the example page to the contributors page.

For example here:
- https://mithril-by-examples.tebe.ch/examples/component-closure-add-item/

So, the name of the author "osban" should be linked to "/contributors/osban/".

**Comment by namangirdhar16** [comment]
hi @tbreuss i would like to work on this issue.

**Comment by tbreuss** [comment]
Great, I'll assign you the issue.

The edit should be made here, I think:
https://github.com/tbreuss/mithril-by-examples/blob/main/_includes/layouts/example.html#L9-L13

If you have any question, let me know.

**Comment by namangirdhar16** [comment]
@tbreuss is this hacktober-accepted ?

**Comment by tbreuss** [comment]
> @tbreuss is this hacktoberfest-accepted ? If yes, do assign the label to this issue.

Yo, it is :)

**Comment by namangirdhar16** [comment]
@tbress thanks, i would like to ask just for the sake of confirmation, what needs to be done here is when a user clicks on the author name is should take them to "/contributors/{{author_name}}/" page, is that right?

**Comment by tbreuss** [comment]
This is right, but you should use the `url` filter as stated in my review.

**Comment by namangirdhar16** [comment]
@tbreuss can you please elaborate i don't get it.
