### ISSUE TITLE
Move button for Live Flems Example towards top of the page

### ISSUE THREAD

**Issue by kevinfiol** [tbreuss/mithril-by-examples#48]
Hey there :wave: great site, I think this is a great (and updated) alternative to the live examples on the official Mithril site.

One small suggestion I have is moving the Live Example buttons closer to the tops of their respective pages (see screenshot of an example). Not saying it should be under the description, but I definitely think it should be closer to the top of the page. My reasoning is three-fold:

1. Many users (including me) may want to see what exactly the demo is before I see the code
2. Flems examples already include the code!
3. I love the site, but I often find myself scrolling *alot* just to get to the live example button on each demo

Thoughts welcome.

![image](https://user-images.githubusercontent.com/4752973/141316903-bdcfc430-9eb3-4854-9bff-383df61e87be.png)

**Comment by tbreuss** [comment]
@kevinfiol Good idea! Will do this.

I would like to add that the layout is quite work-in-progress. But anyway, it has no influence on the position of the preview button.

**Comment by tbreuss** [comment]
Have a version ready with #50. It looks like this now:

<img width="1117" alt="issue-48-flems-button" src="https://user-images.githubusercontent.com/1334161/141418031-d3c99b86-2c7f-42e0-89af-8d2f670fb220.png">

I'll release it later today.

**Comment by tbreuss** [comment]
Released with https://github.com/tbreuss/mithril-by-examples/releases/tag/v0.12.0
