### ISSUE TITLE
Typo: "Life Example" should be "Live Example"

### ISSUE THREAD

**Issue by kevinfiol** [tbreuss/mithril-by-examples#68]
Hey, I think there is a typo here: https://github.com/tbreuss/mithril-by-examples/blob/47cb00599b5cc2641e06035c6bf37587abf4a731/.eleventy.js#L93

I believe the proper term should be "Live Example". Love the new design by the way.

**Comment by tbreuss** [comment]
Thanks a lot. One of these classic typos for german speakers.

**Comment by tbreuss** [comment]
Fixed with 207c0ccd9812fbdccd9927e59fb15c504953b4d8
